# Configuración del servidor
server.port=8080

# Nombre de la aplicación
spring.application.name=smartlogix-bff

# URLs de los microservicios
ms.pedidos.url=http://localhost:8081/api/pedidos
ms.inventario.url=http://localhost:8082/api/inventario