server.port=8084
spring.application.name=smartlogix-bff

# URLs de los microservicios
ms.inventario.url=http://localhost:8082
ms.pedidos.url=http://localhost:8081

# CORS - permite llamadas desde el frontend React
cors.allowed-origins=http://localhost:3000,http://localhost:3001
